# Swagger界面内容配置
swagger:
  title: Demo  API接口文档
  Description: Demo Api Documentation
  version: 1.0.0
  termOfServiceUrl: http://jiangfumei.github.io
  contract:
    name: jiangfumei
    url: http://jiangfumei.github.io
    email: 2515651182@qq.com

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    logSlowSql: true
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
  # Redis
  redis:
    host: 47.94.235.166
    password: jfm666
    #数据库索引  默认为0
    database: 1
    port: 6379
    timeout: 3000

# Mybaits-plus
mybatis:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或分号分隔
  type-aliases-package: com.jfmlc.demo.domain
